### ISSUE TITLE
Boolooping in POCO m5

### ISSUE THREAD

**Issue by Asmodeus-79** [xiaoleGun/treble_build_miku#11]
Can't even run adb command

**Comment by Lotybr** [comment]
This was bad installation or something because my device is also a poco m5 and it's working

**Comment by Lotybr** [comment]
> Can't even run adb command

Didn't you make a kernel for performance or am I crazy? It was something with Inazuma performance since it's here I wanted to mention an error I got in the skyline in the 6gb poco m5 version that literally crashed my app

**Comment by Lotybr** [comment]
> Can't even run adb command

Already tried to install the drivers to manually recognize mine also did not recognize the adb right and just went to install the driver manually in device menagar
