### ISSUE TITLE
Still bootlooping in poco M5

### ISSUE THREAD

**Issue by Asmodeus-79** [xiaoleGun/treble_build_miku#14]
[console-ramoops-0.zip](https://github.com/xiaoleGun/treble_build_miku/files/11995025/console-ramoops-0.zip)

**Comment by xiaoleGun** [comment]
Well, do you can boot others gsi?

**Comment by xiaoleGun** [comment]
From log, lead to reboot reason: boringssl-self-check-failed

**Comment by Asmodeus-79** [comment]
> Well, do you can boot others gsi?

I'm sory for late reply, but I can boot other gsi.... the latest version I can boot into your gsi is MikuUI 0.13.3_2

**Comment by xiaoleGun** [comment]
> > Well, do you can boot others gsi?
> 
> I'm sory for late reply, but I can boot other gsi.... the latest version I can boot into your gsi is MikuUI 0.13.3_2. the same problem happened in PE+ by ponces.

but the same problem happened in trebledroid by PHH, and can you try the next version of boot 0.13.3_2, if boot failed I think find the problem is very fast thanks you

**Comment by Asmodeus-79** [comment]
> > > Well, do you can boot others gsi?
> > 
> > 
> > I'm sory for late reply, but I can boot other gsi.... the latest version I can boot into your gsi is MikuUI 0.13.3_2. the same problem happened in PE+ by ponces.
> 
> but the same problem happened in trebledroid by PHH?, and can you try the next version of boot 0.13.3_2, if boot failed I think find problem is very fast thanks you

yes after that version is not booting

**Comment by xiaoleGun** [comment]
> > > > Well, do you can boot others gsi?
> > > 
> > > 
> > > I'm sory for late reply, but I can boot other gsi.... the latest version I can boot into your gsi is MikuUI 0.13.3_2. the same problem happened in PE+ by ponces.
> > 
> > 
> > but the same problem happened in trebledroid by PHH?, and can you try the next version of boot 0.13.3_2, if boot failed I think find problem is very fast thanks you
> 
> yes after that version is not booting, some of latest gsi have the same problem

plz give me your TG username I will send you new image for test

**Comment by Asmodeus-79** [comment]
> > > > > Well, do you can boot others gsi?
> > > > 
> > > > 
> > > > I'm sory for late reply, but I can boot other gsi.... the latest version I can boot into your gsi is MikuUI 0.13.3_2. the same problem happened in PE+ by ponces.
> > > 
> > > 
> > > but the same problem happened in trebledroid by PHH?, and can you try the next version of boot 0.13.3_2, if boot failed I think find problem is very fast thanks you
> > 
> > 
> > yes after that version is not booting, some of latest gsi have the same problem
> 
> plz give me your TG username I will send you new image for test

@KambingGunung79
