### ISSUE TITLE
华为P10无限循环软启动

### ISSUE THREAD

**Issue by Coconutat** [xiaoleGun/treble_build_miku#18]
机型：华为P10 VTR-AL00  
底层：EMUI 9.0.1.179    
内核：[麒麟盘古内核加KSU](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU)  
***
bug描述：  
开机是可以的，但是开机到3!9!以后进去设置向导没几秒就会重复启动然后3!9!然后进入设置向导然后3!9!这么一个循环。    
***  
GSI版本：[Miku UI TDA v0.19.0](https://github.com/xiaoleGun/treble_build_miku/releases/tag/TDA-0.19.0)    
之后尝试使用[Iceows](https://github.com/Iceows)大佬写的[huawei-creator](https://github.com/Iceows/huawei-creator/tree/android-13)进行修改，依然不能解决。

**Comment by xiaoleGun** [comment]
970没遇到...
