### ISSUE TITLE
お願いします

### ISSUE THREAD

**Issue by Lotybr** [xiaoleGun/treble_build_miku#20]
毎日あなたは私を夢中にさせます、私はミクウイうどんのアップデートを待っていますが、今のところ何もありません、お気に入りのボーカロイドを手に持ってAndroid 14のことを考えて何日も眠れませんでした、起動してください    Google翻訳にかけたので字が汚かったらごめんなさい。

**Comment by xiaoleGun** [comment]
The cost of building Android 14 is huge, and a complete build takes 11 hours because my server performance is weak and there is no sponsorship, which leads to wayne's Udon not being adapted yet

**Comment by Lotybr** [comment]
ご迷惑をおかけして申し訳ありません。新しい更新を非常に楽しみにしています。gsi の更新にご尽力いただき、よろしくお願いします。

**Comment by rsesot** [comment]
虽然我没法提供什么几千几万的赞助,但我乐意长期提供我的服务器和我电脑给您用于构建
如果以下配置可以提供帮助,我乐意立即提供SSH
服务器配置:
CPU: AMD® EPYC 7282 v8Core
RAM: 32G
SSD: 3T
Bandwith: IPv4|IPv6/1Gbps|1Gbps/Unlimited
OS: Debian 12
电脑配置:
CPU: AMD® Ryzen 7 5800H With Radeon Graphics × 16
RAM: 32G
SWAP: 900G
SSD: 1T
Bandwith: Only IPv6/1Gbps|1Gbps/Unlimited
OS: Pop!_OS 22.04 LTS

**Comment by rsesot** [comment]
> The cost of building Android 14 is huge, and a complete build takes 11 hours because my server performance is weak and there is no sponsorship, which leads to wayne's Udon not being adapted yet

虽然我没法提供什么几千几万的赞助,但我乐意长期提供我的服务器和我电脑给您用于构建
如果以下配置可以提供帮助,我乐意立即提供SSH
服务器配置:
CPU: AMD® EPYC 7282 v8Core
RAM: 32G
SSD: 3T
Bandwith: IPv4|IPv6/1Gbps|1Gbps/Unlimited
OS: Debian 12
电脑配置:
CPU: AMD® Ryzen 7 5800H With Radeon Graphics × 16
RAM: 32G
SWAP: 900G
SSD: 1T
Bandwith: Only IPv6/1Gbps|1Gbps/Unlimited
OS: Pop!_OS 22.04 LTS
