### ISSUE TITLE
编译GSI失败

### ISSUE THREAD

**Issue by SkipM4** [xiaoleGun/treble_build_miku#21]
日志及屏幕输出如下
[build.log](https://github.com/xiaoleGun/treble_build_miku/files/13062985/build.log)
[build1.log](https://github.com/xiaoleGun/treble_build_miku/files/13062986/build1.log)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/root/treble_build_miku/treble_app/app/src/main/res/xml/pref_misc.xml:90: AAPT: error: resource string/key_misc_low_gamma_brightness (aka me.phh.treble.app:string/key_misc_low_gamma_brightness) not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 582ms

**Comment by xiaoleGun** [comment]
fixed close issues
