### ISSUE TITLE
Pls build arm64 udon mikuuu

### ISSUE THREAD

**Issue by Lotybr** [xiaoleGun/treble_build_miku#23]

**Comment by xiaoleGun** [comment]
Build completed, delayed due to server issues

**Comment by Lotybr** [comment]
Very fast

**Comment by rsesot** [comment]
> Very fast

@Lotybr if you need MikuUI-Udon-0.1.3-arm64-ab-gapps-20231105-UNOFFICIAL.zip

**Comment by Lotybr** [comment]
谢谢
