### ISSUE TITLE
Pls no-SU build

### ISSUE THREAD

**Issue by LordDemecrius83** [xiaoleGun/treble_build_miku#24]
SU binary causes issues in magisk and Play Integrity/SafetyNet

**Comment by xiaoleGun** [comment]
What I built is already N, and there should be no su binary

**Comment by xiaoleGun** [comment]
Wait for me to check back on the weekend

**Comment by LordDemecrius83** [comment]
> What I built is already N, and there should be no su binary

TDA is indeed N but Udon has SU binary

**Comment by xiaoleGun** [comment]
plz try run system/bin/phh-securize.sh in twrp or termux

**Comment by LordDemecrius83** [comment]
> plz try run system/bin/phh-securize.sh in twrp or termux

Currently, I just deleted it with orangefox
