### ISSUE TITLE
Change the compression format (suggestion)

### ISSUE THREAD

**Issue by BrandonJoe247** [xiaoleGun/treble_build_miku#25]
Hello, I was suggesting that you change the compression format from .zip to .xz or .7z , this will surely increase the compression ratio of these roms significantly and help in getting rid of the GitHub file hosting limits ..

**Comment by xiaoleGun** [comment]
Yes, but I was thinking about DSU

**Comment by inmaldrerah** [comment]
DSU Sideloader is powerful, supporting .xz, .bz2, etc., and most GSI users would use that I think. DSU Sideloader automatically unpacks and repacks the file to .gz, and then installs it. Also, maybe a .img.gz is also slightly better as the image is just a file, not a folder, and the folder info is not important.

**Comment by xiaoleGun** [comment]
Closed https://github.com/xiaoleGun/treble_build_miku/commit/6e0c1ca85c3d2ff0ec85f2c83fbc343b6331f11f.
