### ISSUE TITLE
Random Restarts 

### ISSUE THREAD

**Issue by Evvyinnit** [xiaoleGun/treble_build_miku#27]
Hey! love this gsi. No errors everything works fine. But I'm getting some random restarts here and there. It's completely random. Can't tell why it's happen or how. Anyway to fix it?

**Comment by rama982** [comment]
Not happen on my Infinix Note 30 Pro

**Comment by Evvyinnit** [comment]
> Not happen on my Infinix Note 30 Pro

I'm using a Infinix hot 11 play, it just happened few minutes ago, not a complete restart but, it shows that boot animation. Only takes like 10 seconds.

**Comment by Evvyinnit** [comment]
> Just a heads up, I faced random reboots with GSI on the Infinix Note 10 Pro last year. I think it's a vendor issue. Couldn't fix it since I switched phones.

Can you recommend me a good gsi? I don't wanna go back to stock rom cuz it's full of spy bloatware

**Comment by rama982** [comment]
@Evvyinnit all gsi will have random reboot issues on your phone i believe

**Comment by XNEOFF** [comment]
@Evvyinnit Can I assist you with this issue if you're still facing it!??

**Comment by xiaoleGun** [comment]
emmmm, plz give me the log
