### ISSUE TITLE
How to change the model

### ISSUE THREAD

**Issue by 1145141919555** [xiaoleGun/treble_build_miku#28]
I like this GSI and it works perfectly on my xaga. I want to install it into my main system and use it, but I have tried many methods but cannot change the model

**Comment by XNEOFF** [comment]
Utilize My Module for the Change Model, and install it through Magisk/KernelSu
[Change Model Universal By XNEO](https://github.com/xiaoleGun/treble_build_miku/files/13581811/TrebleGSIPropsByXNEO.zip)

**Comment by LordDemecrius83** [comment]
> Utilize My Module for the Change Model, and install it through Magisk/KernelSu [Change Model Universal By XNEO](https://github.com/xiaoleGun/treble_build_miku/files/13581811/TrebleGSIPropsByXNEO.zip)

Bruh did you just take my module and changed the author name to your name?
