### ISSUE TITLE
I have an error that wasn't in version 0.2.0

### ISSUE THREAD

**Issue by Leotaku-senpai** [xiaoleGun/treble_build_miku#30]
I updated the gsi from scratch and now it's is lagaring everything I do, even if it's on the system interface, it lags, my phone is a poco m5 With 6 GB of RAM

**Comment by xiaoleGun** [comment]
try to format data?

**Comment by Leotaku-senpai** [comment]
> tentar formatar dados?

Yes, I formatted it, I already put it in stock ROM more than 3 times I even installed the gsi product
