### ISSUE TITLE
Bluetooth not working 

### ISSUE THREAD

**Issue by samirgaire10** [xiaoleGun/treble_build_miku#4]
Bluetooth is not working   after installing Miku arm64 ab gapps  on blackview a80 pro  mobile

**Comment by xiaoleGun** [comment]
in my device( Xiaomi 6x) bluetooth is working maybe you should change the vendor

**Comment by xiaoleGun** [comment]
and you used which version

**Comment by samirgaire10** [comment]
Android version 13
