### ISSUE TITLE
请问息屏显示有避免烧屏的算法吗

### ISSUE THREAD

**Issue by Hillton53** [xiaoleGun/treble_build_miku#6]
如题，设备moto S30 pro，我在刷入miku ui之后惊讶的发现居然可以息屏显示（moto没有这个功能），但是很担心这会不会导致烧屏。请问mikuui内有避免烧屏的功能吗？

**Comment by xiaoleGun** [comment]
你是oled还是lcd

**Comment by xiaoleGun** [comment]
应该是没有的

**Comment by Hillton53** [comment]
> 你是oled还是lcd

是oled  （小小的吐个槽，没有屏幕指纹和人脸真硬伤啊.....

**Comment by xiaoleGun** [comment]
这是gsi，屏幕指纹自己可以改源码修，2d人脸不安全
